#include "Buff.h"
#include "Player.h"

// DO NOT EDIT THIS FILE
// WILL BE REPLACED BY OJ SYSTEM
int main() {
    int atk, def, speed;
    std::cin >> atk >> def >> speed;

    Player player(atk, def, speed);

    std::string cmd;

    while (std::cin >> cmd) {
        if (cmd == "add") {
            std::string type;
            std::cin >> type;

            std::string name;
            float multi, addend;
            int duration, priority;

            std::cin >> name >> priority >> addend >> multi >> duration;

            if (type == "power") {
                player.addBuff(Buff(Attribute::POWER, name, priority, addend, multi, duration));
            } else if (type == "defense") {
                player.addBuff(Buff(Attribute::DEFENSE, name, priority, addend, multi, duration));
            } else if (type == "speed") {
                player.addBuff(Buff(Attribute::SPEED, name, priority, addend, multi, duration));
            } else {
                std::cout << "Error add parameter!\n";
            }
        } else if (cmd == "remove") {
            std::string name;
            std::cin >> name;
            player.removeBuff(name);
        } else if (cmd == "parse") {
            player.parse();
        } else if (cmd == "tick") {
            int time;
            std::cin >> time;
            player.tick(time);
        } else if (cmd == "cleanse") {
            player.cleanse();
        } else {
            std::cout << "Error command!\n";
        }
    }
}
